Error: detection of tagged messages was wrong
All messages with keywords were interpreted as tagged messages.
But this is not the same, there are also internal keywords like "nojunk".

Now only the tags are used.
Use https://github.com/protz/thunderbird-stdlib function to detect them. Therefore include the needed functions in the addon, too.